
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WebApplication1.Models
{

using System;
    using System.Collections.Generic;
    
public partial class FORMLUUTRU
{

    public int ID { get; set; }

    public string MAGIANGVIEN { get; set; }

    public Nullable<int> IDTKB { get; set; }

    public Nullable<int> MAXACNHAN { get; set; }

    public Nullable<int> TRANGTHAI { get; set; }

    public Nullable<int> CA { get; set; }



    public virtual TKB TKB { get; set; }

    public virtual GIANGVIEN GIANGVIEN { get; set; }

}

}
